### ISSUE TITLE
3.4.3以降ではサムネイルがレンダリングされず、クラッシュする

### ISSUE THREAD

**Issue by toshia** [moguno/mikutter-subparts-image#6]
mikutter 3.4.3でgtk2 3.0.9にアップデートしたのですが、恐らくそれが原因でクラッシュするようになったようです。なお、gtkのイベントコールバック内で例外を投げているためか、うちの環境ではこの出力の直後にSegmentation Faultしています。めっちゃ上にスクロールしていくと見えます。

```
~/.mikutter/plugin/mikutter-subparts-image/mikutter-subparts-image.rb:342:in `render': undefined method `width' for nil:NilClass (NoMethodError)
    from {MIKUTTER_DIR}/core/mui/cairo_sub_parts_helper.rb:29:in `block (3 levels) in render_parts'
    from {MIKUTTER_DIR}/core/mui/cairo_sub_parts_helper.rb:28:in `save'
    from {MIKUTTER_DIR}/core/mui/cairo_sub_parts_helper.rb:28:in `block (2 levels) in render_parts'
    from {MIKUTTER_DIR}/core/mui/cairo_sub_parts_helper.rb:27:in `each'
    from {MIKUTTER_DIR}/core/mui/cairo_sub_parts_helper.rb:27:in `block in render_parts'
    from {MIKUTTER_DIR}/core/mui/cairo_sub_parts_helper.rb:24:in `save'
    from {MIKUTTER_DIR}/core/mui/cairo_sub_parts_helper.rb:24:in `render_parts'
    from {MIKUTTER_DIR}/core/lib/uithreadonly.rb:22:in `block (2 levels) in singleton class'
    from {MIKUTTER_DIR}/core/mui/cairo_miracle_painter.rb:376:in `render_to_context'
    from {MIKUTTER_DIR}/core/lib/uithreadonly.rb:22:in `block (2 levels) in singleton class'
    from {MIKUTTER_DIR}/core/mui/cairo_miracle_painter.rb:346:in `gen_pixmap'
    from {MIKUTTER_DIR}/core/lib/uithreadonly.rb:22:in `block (2 levels) in singleton class'
    from {MIKUTTER_DIR}/core/mui/cairo_miracle_painter.rb:352:in `gen_pixbuf'
    from {MIKUTTER_DIR}/core/lib/uithreadonly.rb:22:in `block (2 levels) in singleton class'
    from {MIKUTTER_DIR}/core/mui/cairo_miracle_painter.rb:120:in `pixbuf'
    from {MIKUTTER_DIR}/core/lib/uithreadonly.rb:22:in `block (2 levels) in singleton class'
    from {MIKUTTER_DIR}/core/mui/cairo_cell_renderer_message.rb:149:in `render_message'
    from {MIKUTTER_DIR}/core/mui/cairo_cell_renderer_message.rb:128:in `uri='
    from {MIKUTTER_DIR}/core/plugin/gtk/mainloop.rb:10:in `main'
    from {MIKUTTER_DIR}/core/plugin/gtk/mainloop.rb:10:in `mainloop'
    from {MIKUTTER_DIR}/mikutter.rb:63:in `boot!'
    from {MIKUTTER_DIR}/mikutter.rb:92:in `<main>'
```

**Comment by Na0ki** [comment]
mikutter 3.5.1, 3.6.0-developでも上記の問題が発生しました。
頻繁に発生するわけではないですが、たまに落ちると以下のようなログを吐きます。
下記出力の後にセグフォします。
```
error: {MIKUTTER_DIR}/core/mui/cairo_cell_renderer_message.rb:132:in `rescue in uri=': NoMethodError by uri: https://twitter.com/syuu1228/status/820205707538481152 model: #<Message: 820205707538481152 User(@syuu1228) HebrewのWindowsこんな感じ（キモい） https://t.co/iud3Z2mX32>
notice: {MIKUTTER_DIR}/mikutter.rb:78:in `boot!': raise mainloop exception `NoMethodError'
notice: {MIKUTTER_DIR}/mikutter.rb:83:in `error_handling!': catch NoMethodError
/Users/ahiru/.mikutter/plugin/mikutter-subparts-image/mikutter-subparts-image.rb:342:in `render': undefined method `width' for nil:NilClass (NoMethodError)
	from /Users/ahiru/mikutter/source/core/mui/cairo_sub_parts_helper.rb:29:in `block (3 levels) in render_parts'
	from /Users/ahiru/mikutter/source/core/mui/cairo_sub_parts_helper.rb:28:in `save'
	from /Users/ahiru/mikutter/source/core/mui/cairo_sub_parts_helper.rb:28:in `block (2 levels) in render_parts'
	from /Users/ahiru/mikutter/source/core/mui/cairo_sub_parts_helper.rb:27:in `each'
	from /Users/ahiru/mikutter/source/core/mui/cairo_sub_parts_helper.rb:27:in `block in render_parts'
	from /Users/ahiru/mikutter/source/core/mui/cairo_sub_parts_helper.rb:24:in `save'
	from /Users/ahiru/mikutter/source/core/mui/cairo_sub_parts_helper.rb:24:in `render_parts'
	from /Users/ahiru/mikutter/source/core/lib/uithreadonly.rb:22:in `block (2 levels) in singleton class'
	from /Users/ahiru/mikutter/source/core/mui/cairo_miracle_painter.rb:384:in `render_to_context'
	from /Users/ahiru/mikutter/source/core/lib/uithreadonly.rb:22:in `block (2 levels) in singleton class'
	from /Users/ahiru/mikutter/source/core/mui/cairo_miracle_painter.rb:353:in `gen_pixmap'
	from /Users/ahiru/mikutter/source/core/lib/uithreadonly.rb:22:in `block (2 levels) in singleton class'
	from /Users/ahiru/mikutter/source/core/mui/cairo_miracle_painter.rb:359:in `gen_pixbuf'
	from /Users/ahiru/mikutter/source/core/lib/uithreadonly.rb:22:in `block (2 levels) in singleton class'
	from /Users/ahiru/mikutter/source/core/mui/cairo_miracle_painter.rb:121:in `pixbuf'
	from /Users/ahiru/mikutter/source/core/lib/uithreadonly.rb:22:in `block (2 levels) in singleton class'
	from /Users/ahiru/mikutter/source/core/mui/cairo_cell_renderer_message.rb:149:in `render_message'
	from /Users/ahiru/mikutter/source/core/mui/cairo_cell_renderer_message.rb:128:in `uri='
	from /Users/ahiru/mikutter/source/core/plugin/gtk/mainloop.rb:10:in `main'
	from /Users/ahiru/mikutter/source/core/plugin/gtk/mainloop.rb:10:in `mainloop'
	from /Users/ahiru/mikutter/source/mikutter.rb:66:in `boot!'
	from /Users/ahiru/mikutter/source/mikutter.rb:95:in `<main>'
```

**Comment by moguno** [comment]
なんかIssueとリンクできなかったんですが、応急処置しました。
@main_icons[@draw_pos]がnilの時は一枚絵表示モードに入らないようにしました。
